incentivizinggood/vize

imports/api/data/methods.js
imports/startup/client/router.jsx
imports/ui/pages/post-a-job.jsx

Rerouted job posts to use the current user ID rather than query parameters. Much cleaner session flow. Need to test a couple of things, but that shouldn't be difficult. Going ahead and making the pull request.

Job Post Refactor/Refactor

---

imports/api/data/methods.js
imports/api/data/votes.js
imports/startup/client/router.jsx
imports/ui/components/companyReview.jsx
imports/ui/components/voteButtons.jsx
imports/ui/pages/dialog-box.jsx
imports/ui/pages/flag.jsx
server/main.js

You can now place votes on reviews from company profile page, or wherever it is the reviews are rendered.
Only workers can vote, once per review, but not for their own reviews, if they're logged in.

Votes on reviews

---

imports/ui/components/showJobComponent.jsx
imports/ui/pages/home.jsx

- Some small changes.
- Wants to merge it to master before refactoring takes place.

small changes

---

imports/api/data/users.js
imports/ui/if-else.jsx
imports/ui/pages/help.jsx
imports/ui/pages/login.jsx
imports/ui/pages/not-found.jsx
imports/ui/pages/register.jsx
imports/ui/password-changer.jsx

I fixed several of the files that I've been the primary developer on.

Some Fixes

---

.meteor/packages
.meteor/versions
i18n/en.i18n.json
imports/ui/pages/wr_blaze_form.html
imports/ui/pages/write-review.jsx

Begun to set up internationalization framework: added en.i18n.json, added internationalization to wr_blaze_form.html and write-review.jsx

i18n round one

---

i18n/common/en.i18n.json
imports/ui/pages/login.jsx
imports/ui/pages/register.jsx
imports/ui/password-changer.jsx

I added translations to the login, register, and password changer components.

I18n login, register, and password changer

---

client/main.html
client/main.jsx
imports/startup/client/router.jsx
imports/ui/app-root.jsx

Refactored routing to make it more declarative and to give the React component tree a constant root. This is needed for things like React context which is used by the Apollo client. This also improves code quality by following React's functional reactive design.

Refactored routing to make it more declarative

---

i18n/common/en.i18n.json
i18n/common/es.i18n.json
imports/ui/components/company-search-result.jsx
imports/ui/components/write-review-button.jsx
imports/ui/pages/company-search-trial.jsx

Cleaned up the code in `/imports/ui/companyComponent.jsx` and moved it to `/imports/ui/components/company-search-result.jsx`. Also broke out the write review button into a new component. This might be reusable.

Clean up company search result

---

i18n/common/en.i18n.json
i18n/common/es.i18n.json
imports/api/data/reviews.js
imports/api/data/salaries.js
imports/ui/forms/submit-salary-data.html
imports/ui/forms/write-review.html

- Changed reviews location type from Array to String, and updated form
- Added location field to salaries (type String) and updated form
- Added i18n for placeholders, Spanish translation pending
- Made the salaries gender field optional, pending feedback
- I think the autoformatter may have run on the translation files, so if there's an unreasonable amount of translations that may be why

Simplschema location fixes

---

imports/ui/forms/submit-salary-data.html
imports/ui/pages/submit-salary-data.jsx

Salary Form

---

i18n/SimpleSchema/en.i18n.json
i18n/SimpleSchema/es.i18n.json
i18n/common/en.i18n.json
imports/sass/_post-job.scss
imports/ui/forms/post-a-job.html
imports/ui/pages/post-a-job.jsx

Implement Post a Job Form and added styling to it. Changed a few of the translation files because I thought it might be better to not include so many "please"s in the input forms. Let me know if anyone thinks this is not a better approach.

Post a Job Form

---

imports/ui/components/showJobComponent.jsx
imports/ui/pages/showjobs.jsx

I have converted the show jobs page to use GraphQL. This has not been tested because I have no test data.

Convert showjobs to GraphQL

---

client/main.jsx
imports/api/data/users.js

The function `Meteor.user()` only returns a few default fields without a suitable pub/sub connection. I have added the necessary publication and subscription.

Fixed missing data in Meteor.user().

---

i18n/common/en.i18n.json
i18n/common/es.i18n.json
imports/ui/forms/apply-for-job.html
imports/ui/pages/apply-for-job.jsx

Completion of Job Application form along with a minor change to placeholder text

Job Application Form

---

i18n/common/en.i18n.json
i18n/common/es.i18n.json
imports/api/data/reviews.js
imports/sass/_post-job.scss
imports/ui/forms/post-a-job.html
imports/ui/forms/write-review.html
imports/ui/pages/write-review.jsx

Completion of review form. UI is not to perfection but will further improve later on

Review Form

---

.eslintrc.json
imports/api/data/denormalization.js
imports/ui/afInputStarRating.js
imports/ui/components/footer.jsx
imports/ui/components/header.jsx
imports/ui/error-widget.jsx
imports/ui/pages/home.jsx
imports/ui/pages/my-account.jsx
imports/ui/pages/password-changer.jsx

Fixed some miscellaneous lint errors in the UI code and in the denormalization helpers. No functionality should have changed.

Fixed some miscellaneous lint errors

---

imports/api/data/methods.js
imports/api/graphql/resolvers.js
imports/api/graphql/schema.graphql
imports/api/models/vote.js
imports/ui/components/company-profile/sections/reviews.jsx
imports/ui/components/company-profile/tabs/overview.jsx
imports/ui/components/company-profile/tabs/reviews.jsx
imports/ui/components/companyReview.jsx
imports/ui/components/voteButtons.jsx
imports/ui/pages/company-profile.jsx

Changed vote buttons to use GraphQL instead of Meteor's Mongo DDP.

Feature - Migrate vote buttons to GraphQL

---

meteor-app/imports/api/graphql/connectors/postgresql.js
meteor-app/server/main.js

Added automatic database connection test to help catch and debug errors sooner.

Feature - Postgres connection check

---

meteor-app/imports/startup/client/i18n.js
package-lock.json
package.json

I changed the default locale to `es`. Note: the site will still be in English if your browser requests it.

Feature - Set "es" as the default locale

---

meteor-app/imports/api/graphql/.gitignore

For people working with @joshuatshaffer 's pull request before it gets merged

Added ignore line for graphqlgen.js.

---

meteor-app/package-lock.json
meteor-app/package.json

Updated react-dom to fix a vulnerability detected on GitHub.

Hotfix - react-dom vulnerability

---

meteor-app/imports/api/graphql/schema.graphql
meteor-app/imports/api/models/reward-wrote-a-review.js
meteor-app/package-lock.json
meteor-app/package.json

* Added check to limit phone numbers to Mexico.
* Fixed error reporting. The errors had been reported as a normal return value and not proper errors.

Feature - Limit numbers to Mexico

---

meteor-app/imports/api/data/reviews.js
meteor-app/imports/api/data/salaries.js

Made address field optional for review and salary forms. We should remove the address field from the schema but we can do this in the next launch.

Make address field optional

---

meteor-app/imports/api/http/graphql-middleware.ts
meteor-app/imports/api/http/hello-world-middleware.ts
meteor-app/imports/api/http/index.ts
meteor-app/imports/api/http/server.ts
meteor-app/server/main.js

I moved the HTTP server code into its own folder and I broke out the middleware code into separate files for each middleware.

Refactor - HTTP server

---

docs/pagination.md

Sense I have done a lot of research on pagination, I wrote a document about what I learned so that others do not have to repeat all of that research.

Refactor - Pagination conceptual documentation

---

meteor-app/imports/api/models/reward-wrote-a-review.ts

Added slack notification when a user claims a reward.

Feature - Reward claim notification

---

meteor-app/imports/api/connectors/postgresql-old.ts
meteor-app/imports/api/connectors/postgresql.ts
meteor-app/imports/api/graphql/resolvers/mutation.ts
meteor-app/imports/api/graphql/schema.graphql
meteor-app/imports/api/models/vote/vote-mutations.ts
meteor-app/imports/api/models/vote/vote-queries.ts
meteor-app/imports/api/models/vote/vote.ts
meteor-app/imports/ui/components/vote-buttons/vote-button.jsx
meteor-app/imports/ui/components/vote-buttons/vote-buttons.graphql
meteor-app/imports/ui/components/vote-buttons/vote-buttons.jsx
meteor-app/imports/ui/pages/company-profile/company-profile.graphql

* Made the `castVote` mutation.
* Converted vote buttons to use this mutation.
* Included ability to remove votes by clicking its button again.

Feature - Cast vote mutation

---

meteor-app/i18n/common/en.i18n.json
meteor-app/i18n/common/es.i18n.json

-Fixed a grammatical error in the resources page
-Changed home page text

Refining Text

---

meteor-app/imports/api/connectors/postgresql.ts
meteor-app/imports/api/models/company/company-queries.ts
meteor-app/imports/api/models/job-ad/job-ad-queries.ts
meteor-app/imports/api/models/location/location-queries.ts
meteor-app/imports/api/models/review/review-queries.ts
meteor-app/imports/api/models/reward-wrote-a-review.ts
meteor-app/imports/api/models/salary/salary-queries.ts
meteor-app/imports/api/models/vote/vote-mutations.ts
meteor-app/imports/api/models/vote/vote-queries.ts
meteor-app/imports/lib/sql-template.tests.ts
meteor-app/imports/lib/sql-template.ts
meteor-app/package-lock.json
meteor-app/package.json
meteor-app/tsconfig.json

I was having some trouble working with the models so I looked into libraries that could help with SQL. Unfortunately I did not find any that looked good, but I did find one that gave me an idea (https://github.com/felixfbecker/node-sql-template-strings). I copied and improved upon its functionality.
This pull adds a template tag. This template tag allows us to build queries from other queries and values just like templating a string.
For example, in the code below `a` and `b` are equal.
```javascript
const a = sql`SELECT * FROM a_table WHERE price < ${budget}`.toPg();
const b = {
text: "SELECT * FROM a_table WHERE price < $1",
values: [budget]
};
```
This makes writing complex queries much easier.
Note: I have not properly documented this code yet. I want to get moving on the mutations …

Refactor - SQL template strings

---

meteor-app/imports/api/graphql/resolvers/query.ts
meteor-app/imports/api/graphql/resolvers/review.ts
meteor-app/imports/api/graphql/resolvers/salary.ts
meteor-app/imports/api/graphql/resolvers/user.ts
meteor-app/imports/api/graphql/schema.graphql
meteor-app/imports/api/models/comment/comment-queries.ts
meteor-app/imports/api/models/company/company-queries.ts
meteor-app/imports/api/models/job-ad/job-ad-queries.ts
meteor-app/imports/api/models/review/review-queries.ts
meteor-app/imports/api/models/salary/salary-queries.ts
meteor-app/imports/api/models/user/user-queries.ts
meteor-app/imports/api/models/vote/vote-queries.ts

Removed some API stuff that we are not using and should not have.
* Got rid of several unused fields in the API.
* Got rid of some de-anonymizing fields in the API. Namely `author` on `Review`.

Refactor - cull API

---

meteor-app/imports/api/graphql/resolvers/query.ts
meteor-app/imports/api/graphql/schema.graphql
meteor-app/imports/api/models/job-ad/job-ad-queries.ts
meteor-app/imports/ui/pages/show-jobs/show-jobs.graphql
meteor-app/imports/ui/pages/show-jobs/show-jobs.jsx

* The jobs page was broken by a recent refactoring. This pull fixes the jobs page.
* Added a minimal job ad search query to the API.

Hotfix - Job ad search

---

meteor-app/imports/ui/pages/home.jsx
meteor-app/imports/ui/sass/components/_companies-search.scss

Refixed Bar on both the homepage and the companies page

Refixed Search bar

---

meteor-app/imports/ui/pages/apply-for-job/apply-for-job.html
meteor-app/imports/ui/pages/create-company-profile/create-company-profile.html
meteor-app/imports/ui/pages/my-account.jsx
meteor-app/imports/ui/pages/password-changer.jsx
meteor-app/imports/ui/pages/post-a-job/post-a-job.html
meteor-app/imports/ui/pages/submit-salary-data/submit-salary-data.html
meteor-app/imports/ui/pages/write-review/write-review.html
meteor-app/imports/ui/sass/components/_post-job.scss
meteor-app/imports/ui/sass/responsive/_desktop-and-down.scss
meteor-app/imports/ui/sass/responsive/_phones-only.scss
meteor-app/imports/ui/sass/responsive/_tablet-and-down.scss
meteor-app/imports/ui/sass/responsive/_tablet-landscape-and-down.scss

Increased width of forms for mobile and changed a class name for the forms

Increased width of forms for mobile

---

meteor-app/imports/ui/components/flag/flag.jsx
meteor-app/imports/ui/components/header/lang-selector.jsx
meteor-app/imports/ui/components/modals/modal-view.jsx

[React hooks](https://reactjs.org/docs/hooks-intro.html) are really cool. They are a lot cleaner than using classes. I have converted three of our components to use hooks. No functionality has changed.

Refactor - React Hooks

---

README.md

I wrote instructions on how to set up the development environment and run the app. I have also removed the Semaphore badge because we are not using it.

Development Environment Set Up Instructions

---

meteor-app/imports/ui/pages/register/register-form.js
meteor-app/imports/ui/pages/register/register-inner-form.jsx
meteor-app/imports/ui/pages/register/role-input.jsx

Removed bad code that was causing the register form to fail.

FIx Register Form

---

meteor-app/imports/ui/components/companies-search-bar.jsx
meteor-app/imports/ui/pages/about.jsx
meteor-app/imports/ui/pages/company-profile/company-profile.jsx
meteor-app/imports/ui/pages/company-profile/summary.jsx
meteor-app/imports/ui/pages/company-profile/tabs/jobs/job-posting.jsx
meteor-app/imports/ui/pages/company-profile/tabs/reviews.jsx
meteor-app/imports/ui/pages/company-profile/tabs/salaries/salaries.jsx
meteor-app/imports/ui/pages/company-profile/tabs/sections/reviews.jsx
meteor-app/imports/ui/pages/company-profile/tabs/sections/salaries.jsx

Cleaned up the remaining components that where implementing the same behavior over and over again instead of using the `withUpdateOnChangeLocale` higher-order component.

Refactor - Use withUpdateOnChangeLocale HOC

---

meteor-app/imports/ui/components/page-wrapper/page-wrapper.jsx
meteor-app/imports/ui/sass/components/_banner.scss

* Componentized `PageWrapper`'s styles.
* Made the footer sticky. (The footer is placed at the bottom of the page even if the content of the page does not push it down.)

Refactor - Componentize PageWrapper's styles

---

meteor-app/imports/ui/pages/about.jsx
meteor-app/imports/ui/sass/pages/_about.scss

update about typography to be consistent and to look better

update about typography to be consistent

---

meteor-app/imports/api/graphql/schema.graphql
meteor-app/imports/api/models/queries/review.ts

Updated API to allow reviews to be written for any company without an error

Review Any Company

---

meteor-app/imports/api/models/mutations/review.ts

Added more information to the new-review notifications that the server posts to our Slack's log channel.

Added more information to the review log post.

---

meteor-app/imports/ui/components/form-stuff/field/field.tsx
meteor-app/imports/ui/pages/create-review/create-review-inner-form.tsx
meteor-app/imports/ui/pages/create-review/create-review.tsx
meteor-app/imports/ui/translations/en.tsx
meteor-app/imports/ui/translations/es.tsx
meteor-app/package.json
meteor-app/yarn.lock

Added a privacy notice in the write a review form and included a privacy field icon for information that will not be displayed on an individual review.
I also improved the language being used on the form in spanish

Review form/privacy notice

---

meteor-app/imports/ui/app-root.tsx
meteor-app/imports/ui/components/button/add-salary-button.tsx
meteor-app/imports/ui/components/button/index.ts
meteor-app/imports/ui/components/button/write-review-button.tsx
meteor-app/imports/ui/components/company-search-result.tsx
meteor-app/imports/ui/pages/company-profile/summary.tsx
meteor-app/imports/ui/pages/company-profile/tabs/reviews.tsx
meteor-app/imports/ui/pages/company-profile/tabs/salaries/salaries.tsx
meteor-app/imports/ui/pages/company-profile/tabs/sections/reviews.tsx
meteor-app/imports/ui/pages/company-profile/tabs/sections/salaries.tsx
meteor-app/imports/ui/pages/home.tsx
meteor-app/imports/ui/pages/register/register-form.tsx
meteor-app/package.json
meteor-app/yarn.lock

Added Google Analytics and Facebook analytics onto the site. I left the google analytics tracking we already had (okgrow) and added a new package "react-ga" so that we can track events. 
Tracking analytics for web pages and for different buttons.
- A bit of refactoring

Google and Facebook Analytics

---

meteor-app/imports/ui/components/footer.tsx

Underlined the WhatsApp contact number, made it bold, and made it a blue link so that it stands out more to users

UI Improvements to Contact Number

---

meteor-app/imports/ui/components/header/header.tsx
meteor-app/imports/ui/components/header/worker-nav-links.tsx
meteor-app/imports/ui/sass/responsive/_desktop-and-down.scss
meteor-app/imports/ui/translations/en.tsx
meteor-app/imports/ui/translations/es.tsx

Refactored a little bit in the process but still a ton of refactoring to do.

Added write review button as the top option in mobile navigation

---

postgres/migrations/V1.8.1__jobad_add_new_contract_type_options.sql
postgres/migrations/V1.8__jobad_add_new_contract_type_options.sql
scripts/deploy.sh
scripts/get-version-info.sh
scripts/install-deps.sh
scripts/run-dev-mode.sh

Changed the deploy script to exit if one of its steps fails. Fixed the broken migration that was keeping the database from being updated.

Fix deploy

---

meteor-app/imports/ui/app-root.tsx
meteor-app/imports/ui/components/companies-search-bar.tsx
meteor-app/imports/ui/pages/apply-to-job-ad/apply-to-job-ad-form.tsx
meteor-app/imports/ui/pages/company-search/company-search.tsx
meteor-app/imports/ui/pages/create-company/create-company-form.tsx
meteor-app/imports/ui/pages/create-job-ad/create-job-ad-form.tsx
meteor-app/imports/ui/pages/create-review/create-review-form.tsx
meteor-app/imports/ui/pages/register/register-form.tsx

- Hardcoded analytics values so that they work
- Added tracking events for creating a review, registering an account, creating a company, posting a job, searching for a company, and applying for a job.
- Removed local and staging from analytics so that it doesn't mess things up
Extra inspiration:
Changed search bar text field so that it does not reset after searching

Fixed analytics and added new tracking events

---

meteor-app/imports/ui/app-root.tsx
meteor-app/imports/ui/components/companies-search-bar.tsx
meteor-app/imports/ui/components/footer.tsx
meteor-app/imports/ui/pages/apply-to-job-ad/apply-to-job-ad-form.tsx
meteor-app/imports/ui/pages/company-search/company-search.tsx
meteor-app/imports/ui/pages/create-company/create-company-form.tsx
meteor-app/imports/ui/pages/create-job-ad/create-job-ad-form.tsx
meteor-app/imports/ui/pages/create-review/create-review-form.tsx
meteor-app/imports/ui/pages/register/register-form.tsx
meteor-app/imports/ui/sass/base/_reset.scss
meteor-app/imports/ui/sass/responsive/_desktop-and-down.scss
meteor-app/imports/ui/translations/es.tsx

- Changed Font of the website
- Improved translation for "Manager Relationships"
- Removed twitter icon since it is not an active social media atm and could be distracting

Sitewide Changes

---

meteor-app/imports/api/graphql/schema.graphql
meteor-app/imports/api/models/mutations/review.ts
meteor-app/imports/api/models/mutations/salary.ts
meteor-app/imports/api/models/queries/review.ts
meteor-app/imports/lib/inputs/review.ts
meteor-app/imports/ui/pages/create-review/create-review-form.tsx
meteor-app/imports/ui/pages/create-review/create-review.graphql
meteor-app/imports/ui/pages/create-review/create-review.tsx
meteor-app/imports/ui/pages/pages.tsx
meteor-app/imports/ui/pages/review-submitted/review-submitted.tsx
meteor-app/imports/ui/sass/base/_reset.scss
meteor-app/imports/ui/translations/en.tsx
meteor-app/imports/ui/translations/es.tsx
meteor-app/package-lock.json
meteor-app/package.json
meteor-app/yarn.lock
postgres/migrations/V1.10__reviews_referredBy.sql

- Created a referral link for each user based on their user ID
- Added share buttons for referral
- Included extra info on logs to help with paying users
- Other minor improvements

Referral Links for Users

---

meteor-app/imports/api/models/queries/company.ts

Upgraded to proper text search for the company search. Did not add optimizations. In the future we could add a generated column to improve search speeds, but it is fast enough right now.

Text search companies

---

meteor-app/imports/api/http/server.ts
meteor-app/imports/api/models/queries/company.ts

Made `searchForCompanies` return all companies if a search is not given.
Also fixed an issue where the server was not sending session cookies.

Optional text search

---

meteor-app/codegen.yml
meteor-app/imports/api/graphql/resolvers/company.ts
meteor-app/imports/api/graphql/schema.graphql
meteor-app/imports/api/models/queries/company-salary-stats.ts
meteor-app/imports/api/models/queries/index.ts
meteor-app/imports/api/models/types.ts

Added the company salary stats query.

Company salary stats query

---

meteor-app/imports/ui/pages/resources-index/article/article.tsx

Added a simple metric to keep track of the number of articles that have been view using Google Analytics and FB Pixel
Will likely add more analytics in the future

Analytics for resources page

---

docker-compose.yml
scripts/deploy.sh

Upgraded Flyway to the latest version.

Upgraded Flyway

---

web-app/src/pages/company-profile/company-profile.tsx

Fixed the errors with the location on the company profile page. The location was being "processed" multiple times and mutated. This caused it to build up quotes and junk when opening the company profile page.

Fix company profile location

---

.eslintrc.js
.vscode/settings.json
api-server/src/connectors/email.ts
api-server/src/connectors/slack-webhook.ts
api-server/src/models/flags.ts
api-server/src/models/misc.ts
api-server/src/models/mutations/company.ts
api-server/src/models/mutations/job-ad.ts
api-server/src/models/mutations/review.ts
api-server/src/models/mutations/salary.ts
api-server/src/models/mutations/user.ts
api-server/src/models/node/node-id.ts
api-server/src/models/queries/comment.ts
api-server/src/models/queries/resource.ts
api-server/src/models/queries/vote.ts
api-server/src/routes/api.ts
api-server/src/routes/passport.ts
api-server/src/routes/web-app.ts
api-server/src/utils/inputs/company.ts
api-server/src/utils/inputs/job-ad.ts
api-server/src/utils/inputs/location.ts
api-server/src/utils/inputs/review.ts
api-server/src/utils/inputs/salary.ts
api-server/webpack.config.js
package.json
yarn.lock

Fixed and upgraded ESLint and used it to improve code quality on the API server.

Fix ESLint

---

web-app/src/pages/resources-index/components/resource-card.tsx
web-app/src/pages/resources-index/components/topic-card.tsx

semi colons were missing for some reason and that was causing some UI bugs

Fixed UI bugs with resources page

---

README.md
scripts/deploy.sh

Modified the deploy script so that we can now deploy to production. Also, I have documented how to deploy in the `READEME.md` file.

Deploy to production

---

api-server/src/index.ts

Added code to force the app to use encrypted HTTPS in production.

Force https

---

web-app/src/pages/create-job-ad/create-job-ad-form.tsx

Made job ad form go to the job's company's profile page when the job is created.

Fixed create job form redirect

---

api-server/src/graphql/schema.graphql
web-app/src/form-schemas.ts
web-app/src/pages/create-company/create-company-form.tsx
web-app/src/pages/create-job-ad/create-job-ad-form.tsx
web-app/src/pages/create-review/create-review-form.tsx
web-app/src/pages/create-salary/create-salary-form.tsx

Corrected location input types and schemas. Made the `city` and `address` required and `industrialHub` optional.

Location required fields

---

web-app/src/components/button/add-salary-button.tsx
web-app/src/components/button/write-review-button.tsx
web-app/src/components/company-search-result.tsx
web-app/src/components/header/employer-nav-links.tsx
web-app/src/components/header/header.tsx
web-app/src/components/jobs/job-posting.tsx
web-app/src/pages/company-profile/articles/job-ad.tsx
web-app/src/pages/company-profile/articles/ratings-dropdown.tsx
web-app/src/pages/create-company/create-company-form.tsx
web-app/src/pages/create-job-ad/create-job-ad-form.tsx
web-app/src/pages/for-employers/for-employers.tsx
web-app/src/pages/home.tsx
web-app/src/pages/index.ts
web-app/src/pages/login/login.tsx
web-app/src/pages/my-account.tsx
web-app/src/pages/password-changer.tsx
web-app/src/pages/register/register.tsx
web-app/src/pages/resources-index/components/resource-card.tsx
web-app/src/pages/resources-index/components/topic-card.tsx
web-app/src/pages/resources-index/resource/resource.tsx
web-app/src/pages/review-submitted.tsx
web-app/src/pages/show-jobs/show-job-component.tsx
web-app/src/pages/url-generators.ts

Refactored the URL generators.

Refactor url generators

---

.vscode/settings.json
api-server/src/models/mutations/user.ts
api-server/src/models/node/node.ts
api-server/src/models/queries/user.ts
api-server/src/routes/passport.ts
web-app/src/auth.ts
web-app/src/components/register-login-modal.tsx
web-app/src/pages/login/login-form.tsx
web-app/src/pages/login/login-inner-form.tsx
web-app/src/pages/login/login.tsx
web-app/src/pages/register/register-form.tsx
web-app/src/pages/register/register-inner-form.tsx
web-app/src/pages/register/register.tsx
web-app/src/translations/en.tsx
web-app/src/translations/es.tsx

- Made it so that users can login with an email address or username.
- Removed username from register form and api. All new users will have null usernames.
- Refactored front end code a little bit.

Login with email

---

web-app/src/components/jobs/job-posting.tsx
web-app/src/pages/job-ad.graphql
web-app/src/pages/job-ad.tsx
web-app/src/pages/pages.tsx

Made page for job ads so that job ads can be directly accessed by URL.

Job ad URL

---

api-server/src/graphql/schema.graphql
api-server/src/models/queries/company.ts
api-server/src/models/types.ts
postgres/migrations/V1.25__company_icon_url.sql
web-app/src/components/company-search-result.tsx
web-app/src/pages/company-profile/summary.graphql
web-app/src/pages/company-profile/summary.tsx
web-app/src/pages/company-search/company-search.graphql

- Changed the backend to allow for a company profile URL to be inputted for a company.
- Refactored the frontend for the company search component and for the company summary component and made changes so that different sized icons looks good.

Company Profile Icon

---

web-app/src/pages/pages.tsx
web-app/src/pages/privacy-policy.tsx

Added the privacy policy to the site so that it can be viewed at a public URL. www.vize.mx/privacy-policy This privacy policy page is not styled. Styles can be added in another pull request.

Added Privacy policy

---

web-app/src/pages/privacy-policy.tsx

Use "/privacy-policy#data-deletion-instructions" for a direct link to the section in the policy.

Added data deletion instructions to privacy policy

---

web-app/src/pages/not-found.tsx

- Made the 404 page look better.
- Added a return to home link.
- Added translations.

Better 404 page

---

postgres/migrations/V1.21.2__job_ad_salary.sql

This seems to have fixed the error.

Attempting to fix migration.

---

web-app/src/components/companies-search-bar.tsx
web-app/src/components/footer.tsx
web-app/src/components/header/employer-nav-links.tsx
web-app/src/components/header/header.tsx
web-app/src/components/header/worker-nav-links.tsx
web-app/src/pages/company-profile/articles/ratings-dropdown.tsx
web-app/src/pages/company-profile/company-profile.tsx
web-app/src/pages/company-profile/sections/job-ads.tsx
web-app/src/pages/company-profile/sections/reviews.tsx
web-app/src/pages/company-profile/sections/salaries.tsx
web-app/src/pages/create-review/create-review-form.tsx
web-app/src/pages/home.tsx
web-app/src/pages/login/login-form.tsx
web-app/src/pages/login/login.tsx
web-app/src/pages/my-account.tsx
web-app/src/pages/pages.tsx
web-app/src/pages/register/register-form.tsx
web-app/src/pages/register/register.tsx
web-app/src/pages/resources-index/components/back-to-resources-header.tsx
web-app/src/pages/review-submitted.tsx
web-app/src/pages/url-generators.ts
web-app/src/sass/components/_header.scss
web-app/src/translations/en.tsx
web-app/src/translations/es.tsx

Translated all query routes and parameters to spanish to make the UI more friendly to users.
I went ahead and also refactored by making sure that all links use the urlGenerator.
Did a few translations

Translated query routes to spanish

---

api-server/src/routes/passport.ts

Added email to profile fields as suggested in SO post. Will have to test on staging to see if we are getting emails correctly now.

Potentially fixed getting email from Facebook Register

---

api-server/src/models/mutations/job-ad.ts
web-app/src/pages/apply-to-job-ad/apply-to-job-ad-form.tsx
web-app/src/pages/apply-to-job-ad/apply-to-job-ad.graphql
web-app/src/pages/apply-to-job-ad/company-id-from-job-ad-id.graphql
web-app/src/pages/job-application-submitted.graphql
web-app/src/pages/job-application-submitted.tsx
web-app/src/pages/pages.tsx
web-app/src/pages/url-generators.ts
web-app/src/translations/en.tsx
web-app/src/translations/es.tsx

Created the page that users will see after submitting a job application.

Created Job Application Submitted Page

---

api-server/src/models/mutations/user.ts
api-server/src/routes/passport.ts

Fixed some type errors that were preventing deployment to staging from happening.

Fixed user & passport startup errors

---

api-server/src/connectors/email.ts
api-server/src/graphql/schema.graphql
api-server/src/models/mutations/job-ad.ts
web-app/src/pages/apply-to-job-ad/apply-to-job-ad-form.tsx
web-app/src/pages/apply-to-job-ad/apply-to-job-ad.graphql
web-app/src/pages/apply-to-job-ad/apply-to-job-ad.tsx

- Changed our email service from Mailgun to Sendinblue because Mailgun required $35/month subscription in order to be able to reply to emails.
- Added email parameters and message for an email that is sent to workers & employers after a job application is submitted. Email message is in a template in Sendinblue (message me for access if needed).
I built on top of code from my last PR because I needed some of the code from that PR but unfortunately, the changes are showing up here. Need to figure out how to make sure the changes from another PR don't show up (if that's possible).

Send Job Application Emails To Workers and Employers

---

api-server/src/graphql/resolvers/query.ts
api-server/src/models/mutations/job-ad.ts

Forgot to include a return statement

Fix job application bug

---

api-server/package.json
api-server/src/connectors/email.ts
api-server/src/models/mutations/job-ad.ts
api-server/src/models/mutations/user.ts
api-server/src/routes/passport.ts
postgres/migrations/V1.28__password_reset.sql
web-app/src/auth.ts
web-app/src/pages/login/login.tsx
web-app/src/pages/pages.tsx
web-app/src/pages/request-password-reset/index.ts
web-app/src/pages/request-password-reset/request-password-reset-form.tsx
web-app/src/pages/request-password-reset/request-password-reset-inner-form.tsx
web-app/src/pages/request-password-reset/request-password-reset.tsx
web-app/src/pages/reset-password/index.ts
web-app/src/pages/reset-password/reset-password-form.tsx
web-app/src/pages/reset-password/reset-password-inner-form.tsx
web-app/src/pages/reset-password/reset-password.tsx
web-app/src/pages/url-generators.ts
yarn.lock

Made backend, API, and forms for resetting passwords.
Also improved the email connector.

Password reset

---

web-app/src/pages/home.tsx
web-app/src/sass/components/_banner.scss
web-app/src/sass/components/_forms.scss
web-app/src/sass/components/_header.scss
web-app/src/sass/components/_review-form.scss
web-app/src/sass/helpers/_display-helpers.scss
web-app/src/sass/pages/_company-profile.scss
web-app/src/sass/pages/_home.scss
web-app/src/sass/pages/_review-profile.scss
web-app/src/sass/responsive/_desktop-and-down.scss

- Fixed color mismatch on the home screen
- Added border-radius to  write a review and salary components
- Fixed alignment issues with CTA
- Removed background from hover on nav bar buttons

UI Fixes to the home page
