i18n/errors-i18n.js
imports/api/data/companies.js
imports/api/data/jobads.js
imports/api/data/reviews.js
imports/api/data/salaries.js

Made the schema labels and error messages reactive with regards to locale, assuming that the following environment variable assignment is made:
UNIVERSE_I18N_LOCALES="en, es"
My wish list for these features:
- Not having to load all the locales on startup, but being able to load them as needed
- Being able to navigate to the forms for creating a company profile or posting a job without resetting locale, although I guess that's just as much integrating them into the session flow as anything else...

Schema i18n reactivity

---

imports/api/graphql/resolvers.js
imports/api/graphql/schema.graphql
package-lock.json
package.json

Changed the GraphQL API to encode dates and times as strings compliant with the date-time format outlined in the RFC 3339 profile of ISO 8601. For example `"2018-06-23T18:13:47Z"` is the time that I wrote this. 
JavaScript Date objects can be constructed directly from these strings.
```JavaScript
const myDate = new Date("2018-06-23T18:13:47Z");
```
As of yet, no code depends on this part of the API so nothing else was changed.

Iso8601 dates in graphql

---

i18n/common/en.i18n.json
i18n/common/es.i18n.json
imports/api/data/jobads.js
imports/ui/forms/post-a-job.html
imports/ui/pages/post-a-job.jsx

There were two bugs that we (mostly me) failed to catch on Julian's pull request:
- Contract type translations not loading
- Form submission not taking place
- Form error reporting not looking correct
Both have been fixed, but there may need to be additional work done before the form looks correct again:
- Contract type translations were fixed by having them loaded dynamically by a template helper function rather than statically by the schema
- However, this means a new translation will need to be added (you'll see which one if you try to translate the page)
- Form submission and error reporting were "fixed" by removing a form tag that seems to have overridden Autoform's default behaviors. This may require Julian going back through and finding a different way to apply styling to the page.

Post-a-job Form Bug Fixes

---

.gitignore
.meteorignore

Added a `.meteorignore` file to protect non-Meteor files from being loaded by Meteor. This works the same as a `.gitignore`. Also, the `config` and `script` directories have been preemptively setup. `config` contains the settings files which are kept out of version control and `scripts` is unpopulated at the moment but should soon get the database initialization scrips and automatic deployment scripts.

Feature - Meteor Ignore

---

imports/ui/components/header/employer-header.jsx
imports/ui/components/header/header.jsx
imports/ui/components/header/index.js
imports/ui/components/header/lang-selector.jsx
imports/ui/components/header/worker-header.jsx
imports/ui/pages/about.jsx
imports/ui/pages/apply-for-job.jsx
imports/ui/pages/company-profile.jsx
imports/ui/pages/company-search-trial.jsx
imports/ui/pages/contact-us.jsx
imports/ui/pages/foremployers.jsx
imports/ui/pages/home.jsx
imports/ui/pages/my-account.jsx
imports/ui/pages/password-changer.jsx
imports/ui/pages/post-a-job.jsx
imports/ui/pages/resources-employers.jsx
imports/ui/pages/resources-workers.jsx
imports/ui/pages/showjobs.jsx
imports/ui/pages/submit-salary-data.jsx
imports/ui/pages/write-review.jsx

In ES6 one can organize code into modules. All of the module's code is put in one directory and an `index.js` file is created. The `index.js` file exports all of the modules public members. When importing from a module the directory is put as the import path. This helps keep code more readable and maintainable by isolating unrelated files from each other.
I have organized the Header code into a module. 
* All of the files that are used only by the header are now in `/imports/ui/components/header`.
* None of the code was changed except for file renames and imports.

Refactor - Use module pattern for Header

---

imports/api/graphql/resolvers.js

Fixed error where when no user is logged in the API still tries to get the users current vote instead of returning `null` like it should. This caused all queries that fetch `Review.currentUserVote` to fail if the user was not logged in. Also fixed the `Context` type so that Flow will detect this kind of error in the future.

Bugfix - Get current user's vote, user not logged in

---

meteor-app/package.json

Removed pg-live-select because it is not needed.

Bugfix - Remove pg-live-select

---

meteor-app/package-lock.json
meteor-app/package.json

Removed pg-native because it causes the galaxy deployments to crash on install. We don't seem to need it anyway. I have actually been doing this manually when we staged the site so we know this works.

Bugfix - Remove pg-native

---

meteor-app/package-lock.json
package-lock.json
package.json
run.sh

I found some very nice tools while looking through create-react-app's source code.
* Added a pre-commit hook that runs prettier on the files being committed. This will help prevent us from forgetting to format code correctly.
* Added a pre-commit hook to fix any weird file mode changes. All files with the extension `.sh` have their mode set to 755. All other files are set to 644.
* Added dependency installer/updater script to `run.sh`. This installs dependencies for `/package.json`, `/meteor-app/package.json`, and Meteor's special package system.

Refactor - Pre-commit Linting

---

package.json

By default lint-staged tries to run multiple linters at the same time. This causes the linters fail because only one `git add` command can be run at a time. I turned off this concurrency and it works fine now.

Hotfix - lint-staged concurrency

---

meteor-app/imports/ui/app-root.jsx
meteor-app/imports/ui/components/scroll-restoration/index.js
meteor-app/imports/ui/components/scroll-restoration/scroll-restoration.jsx

Made a component that resets the scroll position to the top whenever the user opens a new page. This prevents the user from starting at the bottom of a page when they open it.
P.S. The component is called `ScrollRestoration` because in the future we should enhance it to also _restore_ previous scroll positions when the user goes back a page. For now it only resets the scroll.

Feature - Scroll Restoration

---

docker-compose.dev.yml
meteor-app/Dockerfile-dev
meteor-app/entrypoint-dev.sh
run.sh

* Changed run.sh to use `npm ci` so that the `package-lock.json` files stop changing. 
* Changed the Docker dev testing system to not install NPM packages by itself. If some NPM install operation is needed use `./run.sh i` and restart the testing server.
* One of the Docker volumes, `node-modules`, is no longer needed. You can delete this from your computer to save a little disk space.

Feature - npm ci

---

meteor-app/imports/api/http/graphql-middleware.ts

Allow introspection queries on the production servers so that we can use tools like [Prisma's GraphQL Playground](https://github.com/prisma/graphql-playground/) to test things out.

Bugfix - Allow introspection queries

---

meteor-app/imports/ui/pages/company-profile/summary.jsx

update company link to open the actual URL in a new page with no threats from _blank
<Link> is only used for internal routing 
next time you need to work with eternal routing use 
the usual <a href="...">
https://github.com/ReactTraining/react-router/issues/1147#issuecomment-113180174 
also, don't forget to add  rel="noopener noreferrer"  to fix the _blank vulnerability
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

solved the problem with company URL 

---

meteor-app/imports/api/models/company/company-queries.ts
meteor-app/imports/api/models/job-ad/job-ad-queries.ts
meteor-app/imports/api/models/misc.ts

Added pagination helper for the models. This also fixes a bug where the `totalCount` did not take into account the `WHERE` filters and thus `totalCount` was more than the actual total.

Refactor - Pagination helper

---

.gitignore

Fixed git ignore rules because Meteor generates its own `.gitignore` file when run.

Bugfix - Meteor's gitignore

---

meteor-app/imports/api/connectors/postgresql/postgresql.ts

Removed code that was preventing server processes from shutting down. This code is not needed anyway. 
This bug was causing the server processes to stay alive when they should be shutdown. After a while of working on the app my computer would run out of memory.

Bugfix - Process leak

---

meteor-app/imports/ui/pages/register/register-form.tsx

Fixed register form not sending the users' email addresses to the server.
The server is already setup to save the emails if they are sent. I believe we were thinking that emails should be optional and that is why this was never looked at before. We would benefit from being more clear in our technical requirements.
The server does not require that emails be sent. In the new auth system we should make emails required if we want to have them.

Save users' emails

---

meteor-app/imports/api/graphql/resolvers/mutation.ts
meteor-app/imports/api/graphql/schema.graphql
meteor-app/imports/ui/components/button/write-review-button.tsx
meteor-app/imports/ui/pages/company-profile/company-profile.tsx
meteor-app/imports/ui/pages/create-review/create-review-form.tsx
meteor-app/imports/ui/pages/create-review/create-review-inner-form.tsx
meteor-app/imports/ui/pages/create-review/create-review.graphql
meteor-app/imports/ui/translations/en.tsx
meteor-app/imports/ui/translations/es.tsx

- Changed GraphQL mutation so that creating a review calls the createReview and createSalary resolvers and therefore creates two separate reviews from the same form.
- Front end changes to the form to add the two salary fields and includes privacy text
- Removed salary from company profile because it is currently not a finished product and is not private because each salary is posted separately instead of as a summary.
- Cleaned up some console logs
- Learned a lot of GraphQL :D

Add salary form to review form

---

meteor-app/imports/api/connectors/mongodb.ts

Fixed the issue with MongoDB. It was due to the database name being hard coded to `"meteor"`. The database name should be derived from the MongoDB connection URL.

Fixed MongoDB

---

meteor-app/imports/api/connectors/postgresql.ts
meteor-app/imports/api/http/passport-middleware.ts
meteor-app/imports/api/models/mutations/user.ts
postgres/migrations/V1.13__fix_missing_constraints_on_users.sql

Fixed a race hazard in the `createUser` model. If created at the same time users could have the same username and/or email address as each other. This is fixed by moving constraint checking to the database and not checking it manually.
Similar issues may exist for the other mutations.

Fixed race hazard in `createUser`

---

meteor-app/imports/api/http/passport-middleware.ts
meteor-app/imports/ui/components/login-with-facebook.tsx

Fixed the URLs for the Facebook login. This is needed because the API server's resources were moved under `/api`.

Fix URLs for Facebook login

---

web-app/src/pages/create-review/create-review-form.tsx

Fixed the create review form that was sending some values as strings.
Formik was using the schema to validate the form inputs, but it did not use the result from that validation. Yup parses values when it validates them. So if you give strings representations of the values yup will automatically parse them.

Fixed the create review form

---

web-app/src/components/button/add-salary-button.tsx
web-app/src/components/button/write-review-button.tsx
web-app/src/components/form-stuff/field/field.tsx
web-app/src/components/form-stuff/field/radio-buttons-field.tsx
web-app/src/components/header/lang-selector.tsx
web-app/src/components/login-with-facebook.tsx

Removed all uses of `React.FC` and `React.ComponentType` for typing components because they are not exactly correct and it's easier to just use normal type annotation on the component functions.
A line like `const MyComponent: React.FC<MyComponentProps> = (props) => {` is practically the same as `function MyComponent(props: MyComponentProps): JSX.Element {`.

Removed uses of React.FC and React.ComponentType

---

web-app/package.json
web-app/src/auth.ts
yarn.lock

This partially fixes the error with the login form not handling HTTP errors. `fetch` does not throw errors when getting an HTTP error. Axios will throw on all errors by default.
I have not actually tested this yet.

Switched web app's auth helpers to axios.
